const ecommerce = {
  // stateData: [

  //   {
  //     id: 2,
  //     icon: "local_shipping",
  //     title: "Total Sales",
  //     value: 3100,
  //     growth: 33,
  //     color: "#0A8FDC",
  //   },
  //   {
  //     id: 1,
  //     icon: "point_of_sale",
  //     title: " Returns ",
  //     value: 32100,
  //     growth: 33,
  //     color: "#43C888",
  //   },
  //   {
  //     id: 4,
  //     icon: "supervisor_account",
  //     title: "Campaigns  ",
  //     value: 15000,
  //     growth: 21,
  //     color: "#F04F47",
  //   },
  // ],
  //   // popularProducts: [
  //   //   {
  //   //     id: 1,
  //   //     icon: "/assets/images/dashboard/product_image_1.png",
  //   //     name: "Sports Running Swim",
  //   //     price: 690,
  //   //     mrp: 800,
  //   //   },
  //   //   {
  //   //     id: 2,
  //   //     icon: "/assets/images/dashboard/product_image_2.png",
  //   //     name: "DJI Phantom Camera",
  //   //     price: 430,
  //   //     mrp: 640,
  //   //   },
  //   //   {
  //   //     id: 3,
  //   //     icon: "/assets/images/dashboard/product_image_3.png",
  //   //     name: "Tumble Clothes Dryer",
  //   //     price: 230,
  //   //     mrp: 550,
  //   //   },
  //   //   {
  //   //     id: 4,
  //   //     icon: "/assets/images/dashboard/product_image_4.png",
  //   //     name: "Apple Macbook Display 12 Inch",
  //   //     price: 679,
  //   //     mrp: 800,
  //   //   },
  //   //   {
  //   //     id: 5,
  //   //     icon: "/assets/images/dashboard/product_image_5.png",
  //   //     name: "PBluetooth Speaker",
  //   //     price: 440,
  //   //     mrp: 640,
  //   //   },
  //   //   {
  //   //     id: 6,
  //   //     icon: "/assets/images/dashboard/product_image_6.png",
  //   //     name: "T20 1500 Lumens LCD Projector",
  //   //     price: 233,
  //   //     mrp: 550,
  //   //   },
  //   //   {
  //   //     id: 7,
  //   //     icon: "/assets/images/dashboard/product_image_3.png",
  //   //     name: "Tumble Clothes Dryer",
  //   //     price: 230,
  //   //     mrp: 550,
  //   //   },
  //   //   {
  //   //     id: 8,
  //   //     icon: "/assets/images/dashboard/product_image_4.png",
  //   //     name: "Apple Macbook Display 12 Inch",
  //   //     price: 679,
  //   //     mrp: 800,
  //   //   },
  //   //   {
  //   //     id: 9,
  //   //     icon: "/assets/images/dashboard/product_image_3.png",
  //   //     name: "Tumble Clothes Dryer",
  //   //     price: 230,
  //   //     mrp: 550,
  //   //   },
  //   //   {
  //   //     id: 10,
  //   //     icon: "/assets/images/dashboard/product_image_4.png",
  //   //     name: "Apple Macbook Display 12 Inch",
  //   //     price: 679,
  //   //     mrp: 800,
  //   //   },
  //   //   {
  //   //     id: 11,
  //   //     icon: "/assets/images/dashboard/product_image_5.png",
  //   //     name: "PBluetooth Speaker",
  //   //     price: 440,
  //   //     mrp: 640,
  //   //   },
  //   //   {
  //   //     id: 12,
  //   //     icon: "/assets/images/dashboard/product_image_6.png",
  //   //     name: "T20 1500 Lumens LCD Projector",
  //   //     price: 233,
  //   //     mrp: 550,
  //   //   },
  //   // ],
  // // salesState: [
  // //   {
  // //     id: 1,

  // //     amount: '3510',
  // //     type: 'Turnover',
  // //     icon: '/assets/images/dashboard/auther_sales.svg',
  // //   },
  // //   {
  // //     id: 2,
  // //     amount: '3.2M',
  // //     type: 'Cost of Sales ',
  // //     icon: '/assets/images/dashboard/all_time_sales.svg',
  // //   },
  // //   {
  // //     id: 3,
  // //     amount: '390',
  // //     type: 'Revenue',
  // //     icon: '/assets/images/dashboard/commission_sale.svg',
  // //   },
  // //   // {
  // //   //   id: 5,
  // //   //   amount: '3510',
  // //   //   type: 'Invoices',
  // //   //   icon: '/assets/images/dashboard/icon_revenue.svg',
  // //   // },
  // // ],

  // // salesChartData: [
  // //   {
  // //     name: 'Mon',
  // //     Sales: 8000,
  // //     SalesProfit: 2000,
  // //     SalesLost: 2344,
  // //     NetProfit: 3454,
  // //     margin: 3230,
  // //   },
  // //   {
  // //     name: 'Tue',
  // //     Sales: 6500,
  // //     SalesProfit: 1398,
  // //     SalesLost: 2600,
  // //     NetProfit: 3244,
  // //     margin: 3230,
  // //   },
  // //   {
  // //     name: 'Web',
  // //     Sales: 9800,
  // //     SalesProfit: 2000,
  // //     SalesLost: 2290,
  // //     NetProfit: 5632,
  // //     margin: 6330,
  // //   },
  // //   {
  // //     name: 'Thu',
  // //     Sales: 3908,
  // //     SalesProfit: 1500,
  // //     SalesLost: 2000,
  // //     NetProfit: 4554,
  // //     margin: 3340,
  // //   },
  // //   {
  // //     name: 'Fri',
  // //     Sales: 7000,
  // //     SalesProfit: 3000,
  // //     SalesLost: 2181,
  // //     NetProfit: 4345,
  // //     margin: 3220,
  // //   },
  // //   {
  // //     name: 'Sat',
  // //     Sales: 2390,
  // //     SalesProfit: 3800,
  // //     SalesLost: 2500,
  // //     NetProfit: 4222,
  // //     margin: 5430,
  // //   },
  // //   {
  // //     name: 'Sun',
  // //     Sales: 8000,
  // //     SalesProfit: 3600,
  // //     SalesLost: 2100,
  // //     NetProfit: 2334,
  // //     margin: 3023,
  // //   },
  // // ],
  // // reportData: [
  // //   {
  // //     id: 1,
  // //     value: "785K+",
  // //     type: "Total Sales",
  // //     changes: "10",
  // //     icon: "public",
  // //     color: "#3d5afe",
  // //     graphData: [
  // //       { month: "Aug", number: 310 },
  // //       { month: "Sep", number: 130 },  
  // //       { month: "Oct", number: 350 },
  // //       { month: "Nov", number: 170 },
  // //       { month: "Dec", number: 400 },
  // //     ],
  // //   },
  // //   {
  // //     id: 2,
  // //     value: "$457K+",
  // //     type: "Profit After Cost of Goods",
  // //     changes: "5",
  // //     icon: "pie_chart",
  // //     color: "#F04F47",
  // //     graphData: [
  // //       { month: "Aug", number: 310 },
  // //       { month: "Sep", number: 130 },
  // //       { month: "Oct", number: 350 },
  // //       { month: "Nov", number: 170 },
  // //       { month: "Dec", number: 400 },
  // //     ],
  // //   },
  // //   {
  // //     id: 3,
  // //     value: "565K+",
  // //     type: "Profit After Expenses",
  // //     changes: "15",
  // //     icon: "bar_chart",
  // //     color: "#54B435",
  // //     graphData: [
  // //       { month: "Aug", number: 310 },
  // //       { month: "Sep", number: 130 },
  // //       { month: "Oct", number: 350 },
  // //       { month: "Nov", number: 170 },
  // //       { month: "Dec", number: 400 },
  // //     ],
  // //   },
  // //   {
  // //     id: 4,
  // //     value: "$340K+",
  // //     type: "Margin %",
  // //     changes: "12",
  // //     icon: "account_balance_wallet",
  // //     color: "#0BBFDB",
  // //     graphData: [
  // //       { month: "Aug", number: 310 },
  // //       { month: "Sep", number: 130 },
  // //       { month: "Oct", number: 350 },
  // //       { month: "Nov", number: 170 },
  // //       { month: "Dec", number: 400 },
  // //     ],
  // //   },
  // // ],



  // // revenueData: [
  // //   {
  // //     id: 1,
  // //     name: "Sports Running Swim",
  // //     value: 85,
  // //   },
  // //   {
  // //     id: 2,
  // //     name: "DJI Phantom Camera",
  // //     value: 60,
  // //   },
  // //   {
  // //     id: 3,
  // //     name: "Apple Macbook Display 12 Inch",
  // //     value: 56,
  // //   },
  // //   {
  // //     id: 4,
  // //     name: "PBluetooth Speaker",
  // //     value: 43,
  // //   },
  // //   {
  // //     id: 5,
  // //     name: "DJI Phantom Camera",
  // //     value: 60,
  // //   },
  // //   {
  // //     id: 6,
  // //     name: "Apple Macbook Display 12 Inch",
  // //     value: 56,
  // //   },
  // //   {
  // //     id: 7,
  // //     name: "Sports Running Swim",
  // //     value: 85,
  // //   },
  // //   {
  // //     id: 8,
  // //     name: "PBluetooth Speaker",
  // //     value: 43,
  // //   },
  // // ],
  // bestSellers: [
  //   {
  //     id: 1,
  //     name: "Emma M. Haag",
  //     weekDate: "22 Nov 2020",
  //     profile_pic: "/assets/images/avatar/A10.jpg",
  //     sales: "150",
  //     rating: 5,
  //   },
  //   {
  //     id: 2,
  //     name: "Evelyn F. Means",
  //     weekDate: "20 Nov 2020",
  //     profile_pic: "/assets/images/avatar/A13.jpg",
  //     sales: "145",
  //     rating: 4.5,
  //   },
  //   {
  //     id: 3,
  //     name: "Jamie R. Steen",
  //     weekDate: "22 Dec 2020",
  //     profile_pic: "/assets/images/avatar/A14.jpg",
  //     sales: "140",
  //     rating: 5,
  //   },
  //   {
  //     id: 4,
  //     name: "Jone B. Rilea",
  //     weekDate: "22 Nov 2020",
  //     profile_pic: "/assets/images/avatar/A15.jpg",
  //     sales: "122",
  //     rating: 4.5,
  //   },
  //   {
  //     id: 5,
  //     name: "Emma M. Haag",
  //     weekDate: "19 Nov 2020",
  //     profile_pic: "/assets/images/avatar/A16.jpg",
  //     sales: "104",
  //     rating: 4.5,
  //   },
  //   {
  //     id: 6,
  //     name: "Emma M. Haag",
  //     weekDate: "22 Nov 2020",
  //     profile_pic: "/assets/images/avatar/A10.jpg",
  //     sales: "150",
  //     rating: 5,
  //   },
  //   {
  //     id: 7,
  //     name: "Evelyn F. Means",
  //     weekDate: "20 Nov 2020",
  //     profile_pic: "/assets/images/avatar/A13.jpg",
  //     sales: "145",
  //     rating: 4.5,
  //   },
  //   {
  //     id: 8,
  //     name: "Jamie R. Steen",
  //     weekDate: "22 Dec 2020",
  //     profile_pic: "/assets/images/avatar/A14.jpg",
  //     sales: "140",
  //     rating: 5,
  //   },
  // ],
  // siteVisitors: [
  //   {
  //     id: 1,
  //     color: "green",
  //     value: 45,
  //     icon: "/assets/images/dashboard/us.svg",
  //     country: "USA",
  //   },
  //   {
  //     id: 2,
  //     color: "orange",
  //     value: 98,
  //     icon: "/assets/images/dashboard/fr.svg",
  //     country: "France",
  //   },
  //   {
  //     id: 3,
  //     color: "blue",
  //     value: 86,
  //     country: "Germany",
  //     icon: "/assets/images/dashboard/gr.svg",
  //   },
  //   {
  //     id: 4,
  //     color: "red",
  //     value: 34,
  //     country: "Spain",
  //     icon: "/assets/images/dashboard/es.svg",
  //   },
  //   {
  //     id: 5,
  //     color: "red",
  //     value: 34,
  //     country: "India",
  //     icon: "/assets/images/dashboard/in.svg",
  //   },
  // ],
  // audienceData: [
  //   {
  //     id: 1,
  //     title: "17 - 30 Years old",
  //     value: 30,
  //     color: "#0A8FDC",
  //   },
  //   {
  //     id: 2,
  //     title: "31 - 50 Years old",
  //     value: 25,
  //     color: "#54B435",
  //   },
  //   {
  //     id: 3,
  //     title: ">=50 Year old",
  //     value: 25,
  //     color: "#ff3939",
  //   },
  //   {
  //     id: 4,
  //     title: "20 - 36 Years old",
  //     value: 20,
  //     color: "#F04F47",
  //   },
  // ],
  // topInquiries: [
  //   {
  //     id: 1,
  //     title: "Sports Running Swim",
  //     value: 25,
  //     color: "#0A8FDC",
  //   },
  //   {
  //     id: 2,
  //     title: "Tumble Clothes Dryer",
  //     value: 35,
  //     color: "#54B435",
  //   },
  //   {
  //     id: 3,
  //     title: "PBluetooth Speaker",
  //     value: 20,
  //     color: "#ff3939",
  //   },
  //   {
  //     id: 4,
  //     title: "T20 Lumens LCD Projecto",
  //     value: 20,
  //     color: "#F04F47",
  //   },
  // ],
  // schedules: [
  //   {
  //     id: 1,
  //     title: "Big billion day",
  //     day: 4,
  //     color: "#0A8FDC",
  //   },
  //   {
  //     id: 2,
  //     title: "World Duchenne Awareness Day",
  //     day: 7,
  //     color: "#ff528f",
  //   },
  //   {
  //     id: 3,
  //     title: "Chop Suey Day",
  //     day: 9,
  //     color: "#5269ff",
  //   },
  //   {
  //     id: 4,
  //     title: "Good friday",
  //     day: 12,
  //     color: "#ff3939",
  //   },
  //   {
  //     id: 5,
  //     title: "Birth day",
  //     day: 10,
  //     color: "#F04F47",
  //   },
  //   {
  //     id: 6,
  //     title: "Individual Rights Day",
  //     day: 14,
  //     color: "#63ff52",
  //   },
  //   {
  //     id: 7,
  //     title: "Black friday sale",
  //     day: 20,
  //     color: "#54B435",
  //   },
  // ],

  // marketingCampaign: [
  //   {
  //     id: 1,
  //     name: "Facebook Ads",
  //     description: "63 Likes, 387 Shares",
  //     icon: "/assets/images/dashboard/facebook_icon.png",
  //     graph: 20,
  //     growth: true,
  //     spent: "$125",
  //     duration: "Nov 08-28",
  //     budget: "$450",
  //   },
  //   {
  //     id: 2,
  //     name: "Twitter Ads",
  //     description: "83 Likes, 357 Shares",
  //     icon: "/assets/images/dashboard/twitter_icon.png",
  //     graph: -5,
  //     growth: false,
  //     spent: "$125",
  //     duration: "Nov 08-28",
  //     budget: "$450",
  //   },
  //   {
  //     id: 3,
  //     name: "Instagram",
  //     description: "163 Likes, 587 Shares",
  //     like: "Bicycle",
  //     share: "08-21-2020",
  //     icon: "/assets/images/dashboard/instagram_icon.png",
  //     graph: 20,
  //     growth: true,
  //     spent: "$125",
  //     duration: "Nov 08-28",
  //     budget: "$450",
  //   },
  //   {
  //     id: 4,
  //     name: "LinkedIn",
  //     description: "57 Likes, 250 Shares",
  //     like: "Bicycle",
  //     share: "08-21-2020",
  //     icon: "/assets/images/dashboard/linkedin_icon.png",
  //     graph: 25,
  //     growth: true,
  //     spent: "$125",
  //     duration: "Nov 08-28",
  //     budget: "$450",
  //   },
  //   {
  //     id: 5,
  //     name: "Youtube",
  //     description: "67 Likes, 457 Shares",
  //     like: "Bicycle",
  //     share: "08-21-2020",
  //     icon: "/assets/images/dashboard/youtube_icon.png",
  //     graph: 45,
  //     growth: true,
  //     spent: "$125",
  //     duration: "Nov 08-28",
  //     budget: "$450",
  //   },
  //   {
  //     id: 6,
  //     name: "Dribble",
  //     like: "Bicycle",
  //     description: "80 Likes, 200 Shares",
  //     share: "08-21-2020",
  //     icon: "/assets/images/dashboard/dribble_icon.png",
  //     graph: 25,
  //     growth: true,
  //     spent: "$125",
  //     duration: "Nov 08-28",
  //     budget: "$450",
  //   },
  // ],
  // recentOrders: [
  //   {
  //     id: "#SK231",
  //     customer: "Ina Hughes",
  //     product: "Bicycle",
  //     date: "08-21-2020",
  //     paymentType: "COD",
  //     price: "$125",
  //     status: "Cancelled",
  //   },
  //   {
  //     id: "#SK232",
  //     customer: "Myrtie Ferguson",
  //     date: "08-12-2020",
  //     product: "Addida Shoes",
  //     paymentType: "Prepaid",
  //     price: "$100",
  //     status: "Delivered",
  //   },
  //   {
  //     id: "#SK233",
  //     customer: "Johnny Herrera",
  //     date: "07-30-2020",
  //     product: "Sleeve Jacket",
  //     price: "$1,020",
  //     paymentType: "Prepaid",
  //     status: "Pending",
  //   },
  //   {
  //     id: "#SK234",
  //     customer: "Myrtie Ferguson",
  //     date: "08-12-2020",
  //     product: "Addida Shoes",
  //     paymentType: "Prepaid",
  //     price: "$100",
  //     status: "Delivered",
  //   },
  //   {
  //     id: "#SK235",
  //     customer: "Myrtie Ferguson",
  //     date: "08-12-2020",
  //     product: "Addida Shoes",
  //     paymentType: "Prepaid",
  //     price: "$100",
  //     status: "Delivered",
  //   },
  //   {
  //     id: "#SK236",
  //     customer: "Johnny Herrera",
  //     date: "07-30-2020",
  //     product: "Sleeve Jacket",
  //     price: "$1,020",
  //     paymentType: "Prepaid",
  //     status: "Pending",
  //   },
  //   {
  //     id: "#SK237",
  //     customer: "Ina Hughes",
  //     product: "Bicycle",
  //     date: "08-21-2020",
  //     paymentType: "COD",
  //     price: "$125",
  //     status: "Cancelled",
  //   },
  //   {
  //     id: "#SK238",
  //     customer: "Myrtie Ferguson",
  //     date: "08-12-2020",
  //     product: "Addida Shoes",
  //     paymentType: "Prepaid",
  //     price: "$100",
  //     status: "Delivered",
  //   },
  // ],
  // newCustomers: [
  //   {
  //     id: 10001,
  //     image: "/assets/images/avatar/A1.jpg",
  //     name: "Angelina Joew",
  //     orders: 0,
  //     color: "",
  //     message: "added courses to the new bucket.",
  //   },
  //   {
  //     id: 10002,
  //     image: "/assets/images/avatar/A2.jpg",
  //     name: "John Mathew",
  //     orders: 3,
  //     color: "",
  //     message: "like company website design.",
  //   },
  //   {
  //     id: 10003,
  //     image: "/assets/images/avatar/A3.jpg",
  //     name: "George Bailey",
  //     orders: 3,
  //     color: "",
  //     message: "followed your works",
  //   },
  //   {
  //     id: 10004,
  //     image: "/assets/images/avatar/A4.jpg",
  //     name: "Maria Lee",
  //     orders: 0,
  //     color: "",
  //     message: "liked origmi-creativity agency.",
  //   },
  //   {
  //     id: 10005,
  //     image: "/assets/images/avatar/A1.jpg",
  //     name: "Angelina Joew",
  //     orders: 4,
  //     color: "",
  //     message: "added courses to the new bucket.",
  //   },
  // ],
  // browser: [
  //   {
  //     id: 1,
  //     value: "35K users",
  //     name: "Firefox",
  //     icon: "/assets/images/dashboard/browser_crome.svg",
  //   },
  //   {
  //     id: 2,
  //     value: "39K users",
  //     name: "Safari",
  //     icon: "/assets/images/dashboard/browser_firefox.svg",
  //   },
  //   {
  //     id: 3,
  //     value: "3.2M users",
  //     name: "Google Chrome",
  //     icon: "/assets/images/dashboard/browser_internet_explore.svg",
  //   },
  //   {
  //     id: 4,
  //     value: "3.5M users",
  //     name: "Internet Explorer",
  //     icon: "/assets/images/dashboard/browser_safari.svg",
  //   },
  //   {
  //     id: 5,
  //     value: "3.5M users",
  //     name: "Firefox",
  //     icon: "/assets/images/dashboard/browser_firefox.svg",
  //   },
  // ],

  reportData: [
    {
        id: 1,
        value: "785K+",
        type: "Total Sales",
        changes: "10",
        icon: "public",
        color: "#3d5afe",
        graphData: [
            { month: "Aug", number: 310 },
            { month: "Sep", number: 130 },
            { month: "Oct", number: 350 },
            { month: "Nov", number: 170 },
            { month: "Dec", number: 400 },
        ],
    },
    {
        id: 2,
        value: "$457K+",
        type: "Profit After Cost of Goods",
        changes: "5",
        icon: "pie_chart",
        color: "#F04F47",
        graphData: [
            { month: "Aug", number: 310 },
            { month: "Sep", number: 130 },
            { month: "Oct", number: 350 },
            { month: "Nov", number: 170 },
            { month: "Dec", number: 400 },
        ],
    },
    {
        id: 3,
        value: "565K+",
        type: "Profit After Expenses",
        changes: "15",
        icon: "bar_chart",
        color: "#54B435",
        graphData: [
            { month: "Aug", number: 310 },
            { month: "Sep", number: 130 },
            { month: "Oct", number: 350 },
            { month: "Nov", number: 170 },
            { month: "Dec", number: 400 },
        ],
    },
    {
        id: 4,
        value: "$340K+",
        type: "Margin %",
        changes: "12",
        icon: "account_balance_wallet",
        color: "#0BBFDB",
        graphData: [
            { month: "Aug", number: 310 },
            { month: "Sep", number: 130 },
            { month: "Oct", number: 350 },
            { month: "Nov", number: 170 },
            { month: "Dec", number: 400 },
        ],
    },
],




salesChartData: [
    {
        name: 'Mon',
        Sales: 8000,
        SalesProfit: 2000,
        SalesLost: 2344,
        NetProfit: 3454,
        margin: 3230,
    },
    {
        name: 'Tue',
        Sales: 6500,
        SalesProfit: 1398,
        SalesLost: 2600,
        NetProfit: 3244,
        margin: 3230,
    },
    {
        name: 'Web',
        Sales: 9800,
        SalesProfit: 2000,
        SalesLost: 2290,
        NetProfit: 5632,
        margin: 6330,
    },
    {
        name: 'Thu',
        Sales: 3908,
        SalesProfit: 1500,
        SalesLost: 2000,
        NetProfit: 4554,
        margin: 3340,
    },
    {
        name: 'Fri',
        Sales: 7000,
        SalesProfit: 3000,
        SalesLost: 2181,
        NetProfit: 4345,
        margin: 3220,
    },
    {
        name: 'Sat',
        Sales: 2390,
        SalesProfit: 3800,
        SalesLost: 2500,
        NetProfit: 4222,
        margin: 5430,
    },
    {
        name: 'Sun',
        Sales: 8000,
        SalesProfit: 3600,
        SalesLost: 2100,
        NetProfit: 2334,
        margin: 3023,
    },
],


  expenseProfitData: [
    {
        Costs: 1233,
        OtherRevenue: 500,
        ConProfit: 2000,
        NetProfit: 3453,
        GrossSales: 4000,
        COGS: 2000,
        Marketing: 557,
        Taxes: 200,
        AOV: 50,
        OperationalExpenses: 1000,
        TotalSales: 5000,
        Fulfillment: 6433,
        OrderedProductSales: 3000,
        TransactionFees: 200,
        Returns: 100,
        OrderCount: 50,
        ROAS: 2,
        POAS: 1.5,
        NetMargin: 0.3,
        ConMargin: 0.4,
        date: "Jul-08-2024"
    },
    {
        Costs: 4321,
        OtherRevenue: 600,
        ConProfit: 2500,
        NetProfit: 5547,
        GrossSales: 4500,
        COGS: 2200,
        Marketing: 600,
        Taxes: 250,
        AOV: 55,
        OperationalExpenses: 1200,
        TotalSales: 5500,
        Fulfillment: 333,
        OrderedProductSales: 3500,
        TransactionFees: 250,
        Returns: 150,
        OrderCount: 60,
        ROAS: 2.2,
        POAS: 1.6,
        NetMargin: 0.35,
        ConMargin: 0.45,
        date: "Jul-09-2024"

    },
    {
        Costs: 1334,
        OtherRevenue: 700,
        ConProfit: 2334,
        NetProfit: 2100,
        GrossSales: 400,
        COGS: 2400,
        Marketing: 2343,
        Taxes: 300,
        AOV: 60,
        OperationalExpenses: 1400,
        TotalSales: 6000,
        Fulfillment: 2334,
        OrderedProductSales: 4000,
        TransactionFees: 300,
        Returns: 200,
        OrderCount: 70,
        ROAS: 2.4,
        POAS: 1.7,
        NetMargin: 0.4,
        ConMargin: 0.5,
        date: "Jul-10-2024"

    },
    {
        Costs: 1231,
        OtherRevenue: 800,
        ConProfit: 3500,
        NetProfit: 200,
        GrossSales: 5500,
        COGS: 2600,
        Marketing: 800,
        Taxes: 350,
        AOV: 65,
        OperationalExpenses: 1600,
        TotalSales: 2444,
        Fulfillment: 1600,
        OrderedProductSales: 4500,
        TransactionFees: 350,
        Returns: 250,
        OrderCount: 80,
        ROAS: 2.6,
        POAS: 1.8,
        NetMargin: 0.45,
        ConMargin: 0.55,
        date: "Jul-11-2024"

    },
    {
        Costs: 1231,
        OtherRevenue: 900,
        ConProfit: 4000,
        NetProfit: 2700,
        GrossSales: 4000,
        COGS: 2800,
        Marketing: 900,
        Taxes: 400,
        AOV: 70,
        OperationalExpenses: 1800,
        TotalSales: 4533,
        Fulfillment: 1800,
        OrderedProductSales: 5000,
        TransactionFees: 400,
        Returns: 300,
        OrderCount: 90,
        ROAS: 2.8,
        POAS: 1.9,
        NetMargin: 0.5,
        ConMargin: 0.6,
        date: "Jul-12-2024"

    },
    {
        Costs: 3232,
        OtherRevenue: 1000,
        ConProfit: 4500,
        NetProfit: 3000,
        GrossSales: 3000,
        COGS: 3000,
        Marketing: 1000,
        Taxes: 450,
        AOV: 75,
        OperationalExpenses: 2000,
        TotalSales: 7500,
        Fulfillment: 2000,
        OrderedProductSales: 5500,
        TransactionFees: 450,
        Returns: 233,
        OrderCount: 100,
        ROAS: 3,
        POAS: 2,
        NetMargin: 0.55,
        ConMargin: 0.65,
        date: "Jul-13-2024"

    },
    {
        Costs: 3422,
        OtherRevenue: 1100,
        ConProfit: 5000,
        NetProfit: 3300,
        GrossSales: 7000,
        COGS: 3200,
        Marketing: 200,
        Taxes: 123,
        AOV: 80,
        OperationalExpenses: 2200,
        TotalSales: 4000,
        Fulfillment: 2200,
        OrderedProductSales: 6000,
        TransactionFees: 500,
        Returns: 400,
        OrderCount: 110,
        ROAS: 3.2,
        POAS: 2.1,
        NetMargin: 0.6,
        ConMargin: 0.7,
        date: "Jul-14-2024"

    },
    {
        Costs: 34,
        OtherRevenue: 234,
        ConProfit: 4323,
        NetProfit: 5678,
        GrossSales: 2345,
        COGS: 3453,
        Marketing: 200,
        Taxes: 500,
        AOV: 80,
        OperationalExpenses: 3422,
        TotalSales: 6754,
        Fulfillment: 2345,
        OrderedProductSales: 6755,
        TransactionFees: 353,
        Returns: 242,
        OrderCount: 110,
        ROAS: 3.2,
        POAS: 2.1,
        NetMargin: 0.6,
        ConMargin: 0.7,
        date: "Jul-15-2024"
    }
],




  recentOrder: [
    {
        id: 1,
        name: "Product A",
        platform: "Amazon",
        revenue: 5000,
        quantity: 34,
        profit: 3000,
        date: "2024-07-10"
    },
    {
        id: 2,
        name: "Product B",
        platform: "eBay",
        revenue: 4000,
        quantity: 40,
        profit: 2500,
        date: "2024-07-10"
    },
    {
        id: 3,
        name: "Product C",
        platform: "Magento",
        revenue: 67755,
        quantity: 60,
        profit: 3500,
        date: "2024-07-10"
    },
    {
        id: 4,
        name: "Product C",
        platform: "eBay",
        revenue: 8788,
        quantity: 23,
        profit: 600,
        date: "2024-07-10"
    },
    {
        id: 5,
        name: "Product C",
        platform: "Amazon",
        revenue: 5767,
        quantity: 60,
        profit: 34000,
        date: "2024-03-16"
    },
    {
        id: 6,
        name: "Product C",
        platform: "Magento",
        revenue: 4555,
        quantity: 67,
        profit: 2500,
        date: "2024-07-20"
    },
    {
        id: 7,
        name: "Product C",
        platform: "Shopify",
        revenue: 6000,
        quantity: 4,
        profit: 3500,
        date: " 2024-07-20"
    },
    {
        id: 8,
        name: "Product C",
        platform: "eBay",
        revenue: 456,
        quantity: 3,
        profit: 3500,
        date: " 2024-05-16"
    },
    {
        id: 9,
        name: "Product C",
        platform: "Amazon",
        revenue: 565,
        quantity: 89,
        profit: 3500,
        date: " 2024-07-20"
    },
    {
        id: 10,
        name: "Product C",
        platform: "eBay",
        revenue: 878,
        quantity: 23,
        profit: 500,
        date: " 2024-07-20"
    },
    {
        id: 11,
        name: "Product C",
        platform: "Amazon",
        revenue: 6000,
        quantity: 56,
        profit: 3500,
        date: " 2024-05-16"
    },
    {
        id: 12,
        name: "Product C",
        platform: "Shopify",
        revenue: 8887,
        quantity: 89,
        profit: 900,
        date: " 2024-07-20"
    },
    {
        id: 13,
        name: "Product A",
        platform: "Amazon",
        revenue: 5000,
        quantity: 34,
        profit: 3000,
        date: " 2024-07-10"
    },
    {
        id: 14,
        name: "Product A",
        platform: "Amazon",
        revenue: 5000,
        quantity: 34,
        profit: 3000,
        date: " 2024-07-10"
    },
    {
        id: 15,
        name: "Product A",
        platform: "Amazon",
        revenue: 5000,
        quantity: 34,
        profit: 3000,
        date: " 2024-07-10"
    },
    {
        id: 16,
        name: "Product A",
        platform: "Amazon",
        revenue: 5000,
        quantity: 34,
        profit: 3000,
        date: " 2024-07-10"
    },
    {
        id: 17,
        name: "Product A",
        platform: "Amazon",
        revenue: 5000,
        quantity: 34,
        profit: 3000,
        date: " 2024-07-10"
    },
    {
        id: 18,
        name: "Product A",
        platform: "Amazon",
        revenue: 5000,
        quantity: 34,
        profit: 3000,
        date: " 2024-07-10"
    },
    {
        id: 19,
        name: "Product A",
        platform: "Amazon",
        revenue: 5000,
        quantity: 34,
        profit: 3000,
        date: " 2024-07-10"
    },
    {
        id: 20,
        name: "Product A",
        platform: "Amazon",
        revenue: 5000,
        quantity: 34,
        profit: 3000,
        date: " 2024-07-10"
    },
    {
        id: 21,
        name: "Product A",
        platform: "Amazon",
        revenue: 5000,
        quantity: 34,
        profit: 3000,
        date: " 2024-07-10"
    }
],



revenueData: [
    {
        id: 1,
        name: "Sports Running Swim",
        value: 85,
    },
    {
        id: 2,
        name: "DJI Phantom Camera",
        value: 60,
    },
    {
        id: 3,
        name: "Apple Macbook Display 12 Inch",
        value: 56,
    },
    {
        id: 4,
        name: "PBluetooth Speaker",
        value: 43,
    },
    {
        id: 5,
        name: "DJI Phantom Camera",
        value: 60,
    },
    {
        id: 6,
        name: "Apple Macbook Display 12 Inch",
        value: 56,
    },
    {
        id: 7,
        name: "Sports Running Swim",
        value: 85,
    },
    {
        id: 8,
        name: "PBluetooth Speaker",
        value: 43,
    },
],



  product: [
    {
        id: 1,
        name: "Sports Running Swim",
        price: 690,
        mrp: 800
    },
    {
        id: 2,
        name: "DJI Phantom Camera",
        price: 430,
        mrp: 640
    },
    {
        id: 3,
        name: "Tumble Clothes Dryer",
        price: 230,
        mrp: 550
    },
    {
        id: 4,
        name: "Apple Macbook Display 12 Inch",
        price: 679,
        mrp: 800
    },
    {
        id: 5,
        name: "PBluetooth Speaker",
        price: 440,
        mrp: 640
    },
    {
        id: 6,
        name: "T20 1500 Lumens LCD Projector",
        price: 233,
        mrp: 550
    },
    {
        id: 7,
        name: "Tumble Clothes Dryer",
        price: 230,
        mrp: 550
    },
    {
        id: 8,
        name: "Apple Macbook Display 12 Inch",
        price: 679,
        mrp: 800
    },
    {
        id: 9,
        name: "Tumble Clothes Dryer",
        price: 230,
        mrp: 550
    },
    {
        id: 10,
        name: "Apple Macbook Display 12 Inch",
        price: 679,
        mrp: 800
    },
    {
        id: 11,
        name: "PBluetooth Speaker",
        price: 440,
        mrp: 640
    },
    {
        id: 12,
        name: "T20 1500 Lumens LCD Projector",
        price: 233,
        mrp: 550
    }
]


};
export default ecommerce;
